NorwegianRefugeeCouncil/core

- .github/CODEOWNERS
- .github/pull_request_template.md
Jira ticket: JIRA-CORE24-111
Added CODEOWNERS file to automatically request reviews
Added this PR template.
New PRs have the template ready to be filled, and automatically requests reviews from the team.
None
> task(setup): CORE24-111 Added code owners and PR template

- .github/workflows/ci.yml
- .prettierrc
- nx.json
Jira ticket: JIRA-CORE24-117
Moved the ci config that nx created to the correct location
Updated nx cloud token (read-only)
We need to generate a read-write token and set it to the `NX_CLOUD_ACCESS_TOKEN` env var for github actions.
Build, lint and test scripts should run for PRs, only for the projects that were modified.
> [CORE24-117] task(setup): configured github actions to run lint, tests and build

- README.md
- apps/core-api/project.json
- config/envoy.yaml
- config/oidc-config.json
- docker-compose.yaml
Fixed some prettier errors I missed before in the in local dev env setup PR (since CI wasn't integrated there yet)
In case it helps, for vscode users the following config will use prettier to format specific file types, while using eslint for the types it is defined:
```
{
"editor.codeActionsOnSave": {
"source.fixAll.eslint": "explicit"
},
"[json]": {
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true
},
"[markdown]": {
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true
},
"[dockercompose]": {
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true
},
"[yaml]": {
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true
}
}
```
Build should pass now.
> fix(style): fixed prettier errors in json, yaml and md files

- .github/workflows/cd.yml
> [CORE24-160] task(cd): set default for workflow environment

- apps/core-api/src/main.ts
- apps/core-api/src/middleware/rate-limiter.middleware.ts
* Add keyGenerator to parse ip properly, due to how azure formats it.
* Add trust proxy setting to get real ip from load balancers.
> Handle proxies with rate limiter

- libs/models/src/lib/prm/participant.model.test.ts
- libs/models/src/lib/prm/participant.model.ts
Jira ticket: JIRA-CORE24-#
* Add zod schemas for participant
> Add participant schema

- apps/core-api/src/main.ts
- deploy/terraform/web_app/main.tf
- package.json
- yarn.lock
* Disable cache on frontdoor for selected routes
* Add no cache headers on api for selected routes
* Deploy
* Go to /api/me
* Change user details in okta
* Go to /api/me and see changes update
> Disable caching on api

- apps/core-api/src/controllers/scim.controller.ts
- apps/core-api/src/main.ts
- apps/core-api/src/middleware/error-handler.middleware.ts
- apps/core-api/src/middleware/scim.middleware.ts
- libs/errors/src/lib/errors.ts
- libs/models/src/lib/user.model.test.ts
Just a few issues I noticed while reviewing the latest changes. Mostly removed unused things, and corrected the order for defining the scim error handler middleware
> fix: little cleanup and fixes

- libs/prm-components/src/lib/components/Fields/Checkbox.component.tsx
- libs/prm-components/src/lib/components/Fields/Date.component.tsx
- libs/prm-components/src/lib/components/Fields/Hidden.component.tsx
- libs/prm-components/src/lib/components/Fields/List.component.tsx
- libs/prm-components/src/lib/components/Fields/ReadOnly.component.tsx
- libs/prm-components/src/lib/components/Fields/Select.component.tsx
- libs/prm-components/src/lib/components/Fields/TextArea.component.tsx
- libs/prm-components/src/lib/components/Fields/TextInput.component.tsx
- libs/prm-components/src/lib/components/Fields/index.tsx
- libs/prm-components/src/lib/components/Section.component.tsx
- libs/prm-components/src/lib/config/participant.ts
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
Jira ticket: JIRA-CORE24-206
Opening this as a small pr as it is blocked by the component library
* Add placeholder component for each field type
* Add field component to select component based on field type
* Add section component to render all fields in a section
* Render sections in the page
* Turn the page into a form
* Implement fields after component library is merged
> Core24 206 render create participant form logic 1

- .github/workflows/cd.yml
Jira ticket: JIRA-CORE24-227
Set a fallback for environment in CD config, so it's defined when executed automatically on main branch pushes.
Merge this PR, expect the deployment to be successful.
> [CORE24-227] fix(cd): set fallback value for environment

- apps/core-api-e2e/src/support/global-setup.ts
Jira ticket: JIRA-CORE24-228
Added a wait for the db health check in the global e2e setup.
Note this is based in the integration tests branch, since I had added the health check definition there.
Let CI run e2e tests, expect them to pass consistently.
> [CORE24-228] fix(e2e): wait for db health check when setting up env for tests

- apps/core-api/src/main.ts
- apps/core-frontend/src/main.tsx
- apps/core-frontend/src/styles.scss
- libs/theme/src/lib/theme.ts
- yarn.lock
* Add some css so that the file has content. It was giving a 500 error due to the range header not working with an empty file.
* Rebuild yarn.lock as it was causing some issues with react router
* Only run seeds if directory exists
* Add font settings to the theme
> Frontend fixes

- .github/workflows/ci.yml
- libs/prm-components/src/lib/components/EntityDetailForm.component.tsx
- libs/prm-components/src/lib/components/Fields/Checkbox.component.tsx
- libs/prm-components/src/lib/components/Fields/Display.component.tsx
- libs/prm-components/src/lib/components/Fields/List.component.tsx
- libs/prm-components/src/lib/components/Fields/Select.component.tsx
- libs/prm-components/src/lib/components/Fields/TextArea.component.tsx
- libs/prm-components/src/lib/components/Fields/TextInput.component.tsx
- libs/prm-components/src/lib/components/Section.component.tsx
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.stories.tsx
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.test.tsx
- package.json
- yarn.lock
Jira ticket: JIRA-CORE24-#
* Style entity form
* Add some blocks in when leaving a dirty form
* Styling is based on core v1. Better ui/ux needed in the future but I think this is good enough for now
> Core24 223 render create participant form visuals

- libs/models/src/lib/prm/participant.model.ts
Jira ticket: JIRA-CORE24-271
Schema and model for `ParticipantListItem`
> [CORE24-271] feat(participants): Model for participant list item

- libs/clients/src/lib/prm.client.test.ts
- libs/clients/src/lib/prm.client.ts
- libs/models/src/lib/prm/participant.model.ts
- libs/prm-components/src/lib/components/EntityDetailForm.component.tsx
- libs/prm-components/src/lib/components/Fields/Checkbox.component.tsx
- libs/prm-components/src/lib/components/Fields/Hidden.component.tsx
- libs/prm-components/src/lib/components/Fields/List.component.tsx
- libs/prm-components/src/lib/components/Fields/Select.component.tsx
- libs/prm-components/src/lib/components/Fields/TextInput.component.tsx
- libs/prm-components/src/lib/hooks/useApiReducer.hook.ts
- libs/prm-components/src/lib/hooks/useCreateEntity.hook.ts
- libs/prm-components/src/lib/hooks/useEditEntity.hook.ts
- libs/prm-components/src/lib/hooks/useEntityDetailPage.hook.test.tsx
- libs/prm-components/src/lib/hooks/useEntityDetailPage.hook.ts
- libs/prm-components/src/lib/hooks/useReadEntity.hook.ts
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.module.scss
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.test.tsx
- libs/prm-components/src/lib/prm.context.test.tsx
Jira ticket: JIRA-CORE24-237
Jira ticket: JIRA-CORE24-239
Jira ticket: JIRA-CORE24-41
* Validate payloads and responses in api controller so that default values are sent (eg. sending no email addresses gets parsed to an empty array)
* Configure more optional fields
* Change client to use put for updates
* Use disabled form for read only view
* Ensure correct navigation, data flow, alert showing, etc when switching between create/edit/read modes
* The read only mode looks bad. It's functional but not production ready.
> Core24 237 239 41 finalise entity detail frontend

- apps/core-api/src/controllers/user.controller.ts
- libs/clients/src/lib/prm.client.test.ts
- libs/clients/src/lib/prm.client.ts
- libs/models/src/lib/pagination.model.ts
- libs/models/src/lib/prm/entity.model.ts
- libs/prm-components/src/lib/hooks/useListEntity.hook.test.ts
- libs/prm-components/src/lib/hooks/useListEntity.hook.ts
- libs/prm-components/src/lib/prm.context.test.tsx
- libs/prm-components/src/lib/prm.context.tsx
- libs/test-utils/src/lib/base-test-entity-generator.ts
- libs/test-utils/src/lib/prm/identification.generator.ts
- libs/test-utils/src/lib/prm/participant.generator.ts
Jira ticket: JIRA-CORE24-272
* List client
* useListEntity hook
* Pagination response model
> Core24 272 frontend list data flow

- libs/models/src/lib/index.ts
- libs/models/src/lib/sorting.model.ts
Jira ticket: JIRA-CORE24-221
Schema and model for sorting.
> [CORE24-221] feat(participants): Sorting schema and model

- apps/core-frontend/src/app/app.tsx
- libs/clients/src/lib/prm.client.ts
- libs/prm-components/src/lib/components/EntityDetailForm.component.tsx
- libs/prm-components/src/lib/components/EntityList/EntityList.component.tsx
- libs/prm-components/src/lib/components/Fields/TextArea.component.tsx
- libs/prm-components/src/lib/components/Fields/TextInput.component.tsx
- libs/prm-components/src/lib/components/Pagination.component.test.tsx
- libs/prm-components/src/lib/components/Pagination.component.tsx
- libs/prm-components/src/lib/hooks/useEntityDetailPage.hook.test.tsx
- libs/prm-components/src/lib/hooks/useEntityListPage.hook.ts
- libs/prm-components/src/lib/hooks/usePagination.test.ts
- libs/prm-components/src/lib/hooks/usePagination.ts
- libs/prm-components/src/lib/pages/EntityListPage/EntityListPage.component.tsx
- libs/test-utils/src/lib/prm/participant.generator.ts
Jira ticket: JIRA-CORE24-255
* Improve scrolling behaviour on list page
* improve loading & error states on list page
* Add general use hook for managing pagination state
* Add general use component for pagination
* Integrate pagination into list view
* Currently the page loads an error because the backend isn't configured for this pr. Once the list endpoint work is merged, we should rebase and confirm.
> Core24 255 frontend add pagination

- apps/core-api-e2e/src/support/global-setup.ts
Jira ticket: JIRA-CORE24-228
The sessions middleware creates the sessions table asynchronously, so added a check in the e2e setup to wait for that table to exist before start running tests.
> [CORE24-228] fix(e2e): Explicit check for sessions table before running tests

- libs/prm-components/src/lib/components/EntitySearchForm.component.tsx
- libs/prm-components/src/lib/components/index.ts
- libs/prm-components/src/lib/hooks/useEntityListPage.hook.test.tsx
- libs/prm-components/src/lib/hooks/useEntityListPage.hook.ts
- libs/prm-components/src/lib/pages/EntityListPage/EntityListPage.component.tsx
Jira ticket: JIRA-CORE24-289
added a form component, shown in a drawer on the list page
run the frontend, click on search button
> [CORE24-289] search form, UI

- apps/core-api-e2e/src/core-api/prm/participant.test.ts
- apps/core-api/src/controllers/prm.controller.ts
- libs/db/src/index.ts
- libs/db/src/lib/db-utils.ts
- libs/models/src/lib/prm/entity.model.ts
- libs/models/src/lib/prm/participant.model.ts
- libs/prm-engine/src/lib/services/base.service.ts
- libs/prm-engine/src/lib/services/participant.service.ts
- libs/prm-engine/src/lib/stores/base.store.ts
- libs/prm-engine/src/lib/stores/participant.store.integration.test.ts
- libs/prm-engine/src/lib/stores/participant.store.ts
Jira ticket: JIRA-CORE24-284
Added sorting properties to participant list endpoint, and use them to sort the database results.
Send different sorting parameters, expect the results to be sorted accordingly.
We will need to add some indexes, but I think we should rather do it once we add search/filtering, since the query will likely change a bit more.
> [CORE24-284] feat(participants): Sort list in endpoint

- libs/prm-components/src/lib/config/participant.ts
Jira ticket: JIRA-CORE24-345
display id in detail form
> [CORE24-345] display ID

- libs/prm-components/src/lib/hooks/useEntityDetailPage.hook.ts
- libs/prm-components/src/lib/pages/EntityListPage/EntityListPage.component.tsx
Jira ticket: JIRA-CORE24-343
redirect to list view after entity has been submitted
> [CORE24-343]: redirect to list after submit

- libs/prm-components/src/lib/config/participant.ts
Jira ticket: JIRA-CORE24-358
Re-ordered the individual fields according to the updated spreadsheet.
Go to create/edit/view a individual, check the order and the sections match to what's specified in the Global Registration Form spreadsheet.
There's two missing fields:
- Collect agent title
- Upload agent
That will need to be added once we include roles to the system.
> [CORE24-358] fix(individuals): Correct ordering for fields in form

- libs/prm-components/src/lib/hooks/useCreateEntity.hook.ts
- libs/prm-components/src/lib/hooks/useEntityDetailPage.hook.ts
Jira ticket: JIRA-CORE24-346
reset the data of the context after submitting it.
* click new
* enter data
* submit
* be redirected to list page
* click new again
* form should not contain previously entered data
> [CORE24-346] fix: reset form after submit

- libs/models/src/lib/prm/participant.model.ts
- libs/prm-components/src/lib/hooks/useEntityDetailPage.hook.test.tsx
- libs/prm-engine/src/lib/services/index.ts
- libs/prm-engine/src/lib/services/language.service.test.ts
- libs/prm-engine/src/lib/services/language.service.ts
- libs/prm-engine/src/lib/services/nationality.service.test.ts
- libs/prm-engine/src/lib/services/nationality.service.ts
- libs/prm-engine/src/lib/services/participant.service.test.ts
- libs/prm-engine/src/lib/services/participant.service.ts
- libs/prm-engine/src/lib/stores/language.store.integration.test.ts
- libs/prm-engine/src/lib/stores/language.store.ts
- libs/prm-engine/src/lib/stores/nationality.store.integration.test.ts
- libs/prm-engine/src/lib/stores/nationality.store.ts
Jira ticket: JIRA-CORE24-355
Refined the zod schemas to validate for emails.
Also check date ranges.
And for nationalities and languages, added a check in the service layer to check if the values exist and are enabled.
Added max length limit for all text fields.
Send a wrongly formatted email in the email field when creating/updating an individual, expect to get an 400 error response.
Check for date of birth before 1900 or in the future. Registration date in the future. Non existing countries or languages.
> [CORE24-355] feat(individuals): API validation

- libs/models/src/lib/prm/common.ts
- libs/models/src/lib/prm/participant.model.ts
- libs/prm-components/src/lib/components/EntityDetailForm.component.tsx
- libs/prm-components/src/lib/components/Fields/Checkbox.component.tsx
- libs/prm-components/src/lib/components/Fields/Select.component.tsx
- libs/prm-components/src/lib/components/Fields/TextArea.component.tsx
- libs/prm-components/src/lib/components/Fields/TextInput.component.tsx
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
- package.json
- yarn.lock
Jira ticket: JIRA-CORE24-356
* Add zod resolver to react hook form
* Fixes to get error messages to display
* Set min value on contact details schema so that an empty string fails validation (in most places an empty string is ok, but not in list values as the item should just be removed from the list)
* Set min value on isocode schema so that sending the default value of the select (`""`) causes an error
* Enter a value that is too long
* Enter an empty value for contact details
* Enter a default select value for language/nationality
> Core24 356 frontend validate form data on submit button click display errors

- libs/clients/src/lib/prm/prm-base.client.ts
- libs/prm-components/src/lib/hooks/useEntityListPage.hook.ts
- libs/prm-components/src/lib/hooks/useListEntity.hook.test.ts
- libs/prm-components/src/lib/hooks/useListEntity.hook.ts
- libs/prm-components/src/lib/pages/EntityListPage/EntityListPage.component.tsx
Jira ticket: JIRA-CORE24-349
* Pass sort through data handling of frontend
* Add sorting to base client
* Load list page
* Check network has default sort for participants in request
* List should be sorted by default sort
> Core24 349 frontend send sort payload to client

- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
> Use correct schema when validating edit form

- libs/models/src/lib/prm/common.ts
- libs/models/src/lib/prm/household.model.ts
- libs/models/src/lib/prm/participant.model.ts
Jira ticket: JIRA-CORE24-406
Added the Household model for its creation, plus some extra definitions that will be needed later on
> [CORE24-406] feat(households): created models

- libs/prm-components/src/lib/components/FilterTags.component.tsx
- libs/prm-components/src/lib/components/Sorting.component.tsx
- libs/prm-components/src/lib/hooks/useSorting.hook.test.ts
- libs/prm-components/src/lib/hooks/useSorting.hook.ts
- libs/prm-components/src/lib/pages/EntityListPage/EntityListPage.component.tsx
Jira ticket: JIRA-CORE24-302
* Add hook to manage sorting
* Add component for sorting controls
* Add sorting to entity list view
* Cleanup some divs on the entity list page
* Sort the list page, see correct sorting order
> Core24 302 frontend add sort control

- libs/db/migrations/20240617130635_create_household.ts
Jira ticket: JIRA-CORE24-405
created db table for households according to GRF specs and our discussion
location has to be added later, when we have introduces sites
> [CORE24-405] feat(HH): create db table

- libs/db/migrations/20240617130635_create_household.ts
- libs/models/src/lib/prm/index.ts
- libs/prm-components/src/lib/components/EntityDetailForm.component.tsx
- libs/prm-components/src/lib/config/config.types.ts
- libs/prm-components/src/lib/config/houseHold.ts
- libs/prm-engine/src/lib/stores/household.store.integration.test.ts
- libs/prm-engine/src/lib/stores/household.store.ts
- libs/prm-engine/src/lib/stores/index.ts
- libs/test-utils/src/lib/prm/household.generator.ts
- libs/test-utils/src/lib/prm/index.ts
Jira ticket: JIRA-CORE24-403
created a rudimentary household store and a generator
the linking of households and individuals is happening in JIRA-CORE24-274
had to skip the integration test for now, since individuals are not linked yet
> [CORE24-403] feat(households): rudimentary household store

- apps/core-api/src/controllers/prm.controller.ts
- libs/clients/src/lib/prm/household.ts
- libs/clients/src/lib/prm/individual.ts
- libs/clients/src/lib/prm/prm-base.client.ts
- libs/prm-components/src/lib/config/index.ts
- libs/prm-components/src/lib/hooks/useCreateEntity.hook.ts
- libs/prm-engine/src/lib/services/base.service.ts
- libs/prm-engine/src/lib/services/household.service.ts
- libs/prm-engine/src/lib/services/individual.service.ts
> Move validation into create mixin

- apps/core-frontend/index.html
- apps/core-frontend/src/styles.scss
- libs/prm-components/src/lib/components/Fields/Select.component.tsx
- libs/prm-components/src/lib/components/Sorting.component.tsx
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.test.tsx
- libs/prm-components/src/lib/pages/EntityListPage/EntityListPage.test.tsx
- libs/prm-components/vite.config.ts
- libs/prm-components/vitest.window-setup.js
- package.json
- yarn.lock
Jira ticket: JIRA-CORE24-428
* Add `chakra-react-select` package (a wrapper around react select to use chakra ui styles)
* Use react select for select fields
* If a field has more than 300 rows, use an async select for performance
* Filtering is done in memory and seems performant
* Use react select in sorting component for consistent design
> Core24 428 language selection issue

- apps/core-frontend/src/hooks/useAxiosInstance.hook.ts
- libs/errors/src/lib/formatters.ts
- libs/prm-components/src/lib/components/EntityDetailForm.component.tsx
- libs/prm-components/src/lib/components/Sorting.component.tsx
- libs/prm-components/src/lib/pages/EntityDetailPage/EntityDetailPage.component.tsx
> Core24 357 frontend display validation response from api
